AWSTemplateFormatVersion: "2010-09-09"
Description: "user service stack"
Parameters:
  AppEnv:
    Type: String
    Default: dev
    Description: The environment profile the app will be deployed in
  AppName:
    Type: String
    Default: dev-user-service
    Description: The application name
  ServiceName:
    Type: String
    Description: The service name
  ServicePort:
    Type: Number
    Description: The service port number
  CommitHash:
    Type: String
    Description: Hash of the most recent code commit (This is the tag for the container)
Resources:

  # MicroService
  MicroService:
    Type: AWS::ECS::Service
    DependsOn: ApiListener
    Properties:
      ServiceName: !Sub '${AppEnv}-${ServiceName}'
      Cluster: !Sub '{{resolve:secretsmanager:SecretString:ClusterName}}'
      TaskDefinition: !Ref ServiceTask
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:PrivateSubnetA}}'
            - !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:PrivateSubnetB}}'
          SecurityGroups:
            - !Sub '{{resolve:secretsmanager:${AppName}/${AppEnv}/secrets/resources:SecretString:SecurityGroup}}'
      LoadBalancers:
        - ContainerName: !Sub '${AppName}-${AppEnv}-${ServiceName}'
          ContainerPort: !Ref ServicePort
          TargetGroupArn: !Ref ServiceTargetGroup


  # Task Definition for the MicroService
  ServiceTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppEnv}-${AppName}'
      RequiresCompatibilities:
        - FARGATE
      Memory: 2048
      Cpu: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub '{{resolve:secretsmanager:SecretString:TaskExecutionRole}}'
      TaskRoleArn: !Sub '{{resolve:secretsmanager:SecretString:ContainerExecutionRole}}'
      ContainerDefinitions:
        - Name: !Sub '${AppEnv}-${ServiceName}'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}/${AppEnv}/${ServiceName}:${CommitHash}'
          PortMappings:
            - ContainerPort: !Ref ServicePort
          Environment:
#            environment variables from secrets manager
            - Name: TWILIO_SID
              Value: '{{resolve:secretsmanager:twilio/sid_token:SecretString:TWILIO_SID}}'
            - Name: TWILIO_TOKEN
              Value: '{{resolve:secretsmanger:twilio/sid_token:SecretString:TWILIO_TOKEN}}'
            - Name: JWT_SECRET
              Value: '{{resolve:secretsmanger:jwt/key:JWT_SECRET}}'
            - Name: DB_USER
              Value: '{{resolve:secretsmanger:rds/eastcoders-db/login:SecretString:username}}'
            - Name: DB_PASS
              Value: '{{resolve:secretsmanger:rds/eastcoders-db/login:SecretString:password}}'
          Essential: true
          Memory: 2048
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub ${AppName}/${AppEnv}/${ServiceName}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub ${ServiceName}-${AppEnv}
              awslogs-create-group: 'true'

  # The TargetGroup for the MicroService
  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ServicePort
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: '/health'
      HealthCheckTimeoutSeconds: 5
      HealthCheckPort: !Ref ServicePort
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      TargetType: ip
      VpcId: !Sub '{{resolve:secretsmanager:SecretString:VpcId}}'

  # API Listener
  ApiListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Sub '{{resolve:secretsmanager:SecretString:LoadBalancer}}'
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ServiceTargetGroup
      Port: !Ref ServicePort
      Protocol: HTTP