apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  namespace: eastcoders
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8222
    targetPort: 8222
  selector:
      app: banking
      type: api
      tier: backend