- name: Deploy user-service to eks cluster
  hosts: localhost
  tasks:
  - name: Deploy user-api Service
    shell: |
      kubectl apply -f ../kubernetes-resources/user-api-service.yml

  - name: Deploy user-api
    shell: |
      kubectl apply -f ../kubernetes-resources/user-api-deployment.yml